version: "3.8"
   
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /usr/local/bin/wkhtmltopdf:/usr/bin/wkhtmltopdf
    ports:
      - "8000:8000"